var wmOrder = {
    "messageCode": "1004",
    "Message": "Successful",
    "Orders": [
        {
            "OrderId": 3218483,
            "Status": "P",
            "MerchantId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
            "UserId": "95ccb42f-3ce9-4a89-88ba-13072067409f",
            "TotalAmount": 51130.79,
            "AmountPayable": 51130.79,
            "OrderDate": "/Date(1559717411000+0530)/",
            "BillFirstname": "",
            "BillLastname": "",
            "BillCountry": "India",
            "BillingState": "Maharashtra",
            "BillCity": "BHIWANDI",
            "BillEmail": "",
            "BillZIP": "722184",
            "BillPhone": "-",
            "BillMobile": "91-9741822326",
            "BillAddress1": "",
            "ShipFirstname": "",
            "ShipLastname": "",
            "ShipCountry": "India",
            "ShipState": "Maharashtra",
            "ShipCity": "BHIWANDI",
            "ShipEmail": "",
            "ShipZip": "722184",
            "ShipPhone": "-",
            "ShipMobile": "91-9741822326",
            "ShipAddress1": "",
            "ShipOtherCity": null,
            "DeliveryOption": "ship",
            "TAXTotal": 0,
            "VoucherCode": "",
            "LeadTime": "",
            "BillAddress2": "",
            "ShipAddress2": "",
            "IsGift": false,
            "SupplierID": "00000000-0000-0000-0000-000000000000",
            "ConversionFactor": "1",
            "cpuserid": "00000000-0000-0000-0000-000000000000",
            "OrderLineId": [
                {
                    "OrderLineId": 24792033,
                    "OrderId": 3218483,
                    "ProductId": 243086,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 10,
                    "ShippingCost": 0,
                    "ProductPrice": 81,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "59083",
                    "VariantSku": "",
                    "ProductTitle": "Surf Excel Detergent Bar 4U X 200 g each",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/59083.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00006661",
                    "CategoryName": "Detergent Bar",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792037,
                    "OrderId": 3218483,
                    "ProductId": 212935,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 50,
                    "ShippingCost": 0,
                    "ProductPrice": 106.93,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "405996",
                    "VariantSku": "",
                    "ProductTitle": "Parle-G Biscuits , 24 N (70 g Each)",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/405996_1.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00002549",
                    "CategoryName": "Glucose & Milk",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792043,
                    "OrderId": 3218483,
                    "ProductId": 212931,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 600,
                    "ShippingCost": 0,
                    "ProductPrice": 8.91,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "55926",
                    "VariantSku": "",
                    "ProductTitle": "Parle-G Biscuits 140 g",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/55926_1.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00002549",
                    "CategoryName": "Glucose & Milk",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792047,
                    "OrderId": 3218483,
                    "ProductId": 306394,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 60,
                    "ShippingCost": 0,
                    "ProductPrice": 12.28,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "709621",
                    "VariantSku": "",
                    "ProductTitle": "Clinic Plus Shampoo Strong & Long, 16N ( 6 ml Each)",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/709621.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00002961",
                    "CategoryName": "Shampoo",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792049,
                    "OrderId": 3218483,
                    "ProductId": 365436,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 48,
                    "ShippingCost": 0,
                    "ProductPrice": 52.24,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "455353",
                    "VariantSku": "",
                    "ProductTitle": "Parle 20-20 Biscuits Cashew Cookies, 12 N (45 g Each)",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/455353_1.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00002545",
                    "CategoryName": "Cookies & Bakery Biscuits",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792051,
                    "OrderId": 3218483,
                    "ProductId": 212932,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 24,
                    "ShippingCost": 0,
                    "ProductPrice": 54,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "406017",
                    "VariantSku": "",
                    "ProductTitle": "Parle-G Biscuits , 30 N ( 25 g Each)",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/406017_1.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00002549",
                    "CategoryName": "Glucose & Milk",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792053,
                    "OrderId": 3218483,
                    "ProductId": 276238,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 6,
                    "ShippingCost": 0,
                    "ProductPrice": 42,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "645011",
                    "VariantSku": "",
                    "ProductTitle": "Parle Orange Bite Toffee 100 N ( Rs.0.50 Each)",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/645011_1.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00002520",
                    "CategoryName": "Toffee, Candy & Eclairs",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792055,
                    "OrderId": 3218483,
                    "ProductId": 212862,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 6,
                    "ShippingCost": 0,
                    "ProductPrice": 40,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "430258",
                    "VariantSku": "",
                    "ProductTitle": "Parle Mango Bite Candy 50 N ( Rs. 0.50 Each)",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/430258_1.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00002520",
                    "CategoryName": "Toffee, Candy & Eclairs",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792057,
                    "OrderId": 3218483,
                    "ProductId": 248340,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 1296,
                    "ShippingCost": 0,
                    "ProductPrice": 8.79,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "462283",
                    "VariantSku": "",
                    "ProductTitle": "Lifebuoy Soap Total, 56 g",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/462283.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00005911",
                    "CategoryName": "Soaps",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792059,
                    "OrderId": 3218483,
                    "ProductId": 211012,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 60,
                    "ShippingCost": 0,
                    "ProductPrice": 24.4,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "458776",
                    "VariantSku": "",
                    "ProductTitle": "Surf Excel Detergent Bar 250 g",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/458776_1.JPG;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00006661",
                    "CategoryName": "Detergent Bar",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792061,
                    "OrderId": 3218483,
                    "ProductId": 395360,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 6,
                    "ShippingCost": 0,
                    "ProductPrice": 122.38,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "980011540",
                    "VariantSku": "",
                    "ProductTitle": "Lizol & Harpic Toilet & Floor Cleaner Combi Pack, 500 ml & 500 ml",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/Image-comingsoon.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00006667",
                    "CategoryName": "Cleaning Tools",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792063,
                    "OrderId": 3218483,
                    "ProductId": 212929,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 480,
                    "ShippingCost": 0,
                    "ProductPrice": 8.11,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "55975",
                    "VariantSku": "",
                    "ProductTitle": "Parle Monaco Salt Biscuits Salted, 75.4 g",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/55975_1.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00002546",
                    "CategoryName": "Crackers, Sweet & Salty",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792065,
                    "OrderId": 3218483,
                    "ProductId": 300918,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 120,
                    "ShippingCost": 0,
                    "ProductPrice": 103.44,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "677988",
                    "VariantSku": "",
                    "ProductTitle": "Surf Excel Detergent Powder Easy Wash , 1 kg",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/677988_S1.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00006659",
                    "CategoryName": "Detergent Powder",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792067,
                    "OrderId": 3218483,
                    "ProductId": 216994,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 24,
                    "ShippingCost": 0,
                    "ProductPrice": 36.64,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "462360",
                    "VariantSku": "",
                    "ProductTitle": "Pears Soap Pure & Gentle, 75 g",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/DSC_0435.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00005911",
                    "CategoryName": "Soaps",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792069,
                    "OrderId": 3218483,
                    "ProductId": 244498,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 150,
                    "ShippingCost": 0,
                    "ProductPrice": 8.76,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "568473",
                    "VariantSku": "",
                    "ProductTitle": "Dettol Original Soap 45 g",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/568473.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00005911",
                    "CategoryName": "Soaps",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792071,
                    "OrderId": 3218483,
                    "ProductId": 412422,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 24,
                    "ShippingCost": 0,
                    "ProductPrice": 47.33,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "980013322",
                    "VariantSku": "",
                    "ProductTitle": "Axe Ticket Deo Champion, 17 ml",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/980013322_1.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00003281",
                    "CategoryName": "Men's Deos & Sprays",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                },
                {
                    "OrderLineId": 24792073,
                    "OrderId": 3218483,
                    "ProductId": 217034,
                    "VariantProductId": 0,
                    "IsParentProduct": false,
                    "Description": "",
                    "Quantity": 9,
                    "ShippingCost": 0,
                    "ProductPrice": 152.33,
                    "TotalPromotionDiscount": 0,
                    "ReturnReason": "",
                    "ReturnAction": "",
                    "StockAction": "",
                    "ReturnQty": 0,
                    "IsBackOrder": false,
                    "TotalVoucherDiscount": 0,
                    "TotalTaxAmount": 0,
                    "ShippingVoucherDiscount": 0,
                    "CustomFields": "",
                    "VariantMasterProductId": 0,
                    "LocationCode": "4816",
                    "ShippingStatus": "",
                    "DeliveryMode": "H",
                    "VendorId": "2f9b7c67-7c32-4267-9132-abb503dc4c83",
                    "ItemStatus": "",
                    "SKU": "76485",
                    "VariantSku": "",
                    "ProductTitle": "Axe Deodorant Dark Temptation, 150 ml",
                    "BundleProductId": "0",
                    "ParentReDetailsId": "0",
                    "ImageUrl": "//wm-images-cdn.azureedge.net/azure/wm-resources/2f9b7c67-7c32-4267-9132-abb503dc4c83/Images/ProductImages/Source/76485_S1.jpg;width=100;height=100;scale=canvas;anchor=bottomcenter",
                    "IsPrimaryProduct": "false",
                    "Portion": "",
                    "TaxDetails": [],
                    "LocationId": 262,
                    "CategoryId": "CK00003281",
                    "CategoryName": "Men's Deos & Sprays",
                    "CancelQuantity": 0,
                    "DerivedStatus": "Pending",
                    "DerivedStatusCode": "P",
                    "EstimatedDeliveryTime": "01-Jan-0001 12:00:00 AM",
                    "PromotionIds": null,
                    "SubStatus": "",
                    "IsFreebie": false,
                    "FreebieParent": ""
                }
            ],
            "PaymentDetails": [
                {
                    "PointsBurned": "0",
                    "AgentId": "",
                    "GV": "",
                    "Channel": "W",
                    "CurrencyCode": "INR",
                    "PaymentResponse": "",
                    "PaymentStatus": "P",
                    "Amount": "51130.7891",
                    "PaymentDate": "6/5/2019 12:20:11 PM",
                    "PaymentType": "TPG",
                    "OrderId": 3218483,
                    "PaymentDetailsId": 3920493,
                    "checkOutGroup": "",
                    "PaymentOption": "BankGuarantee",
                    "clientIP": "",
                    "ResponseCode": "N",
                    "ClientUserAgent": "API"
                }
            ],
            "Rewards": null,
            "ShippingDiscount": 0,
            "VoucherDiscount": 0,
            "PromotionDiscount": 0,
            "OriginalOrderId": "",
            "ReturnOrderId": "",
            "ReferenceNo": "",
            "DemandedDeliveryDate": "",
            "deliveryslots": {
                "StartTime": "",
                "EndTime": "",
                "DeliverySlotId": null
            },
            "PickupFirstName": "",
            "PickupLastName": "",
            "PickupEmail": "",
            "PickupMobile": "",
            "Latitude": "0",
            "Longitude": "0",
            "ShippingMode": "Door Step Delivery",
            "GiftMessage": "",
            "RefundAmount": "0",
            "ChannelID": "0",
            "IsSelfShip": "False",
            "ChannelOrderID": "0",
            "Promotions": null,
            "SubStatus": "",
            "OrderAttributes": null,
            "SourceLocationID": "262",
            "SourceLocationCode": "4816",
            "OrderDateLocal": "05-Jun-2019 12:20:11 PM",
            "AutoUpdateTime": "/Date(1560146860808+0530)/",
            "TimeZone": "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi"
        }
    ],
    "ErrorCode": 0
}


function sumWM() {
    var order = wmOrder.Orders[0];

    var totalQty = order.OrderLineId.reduce((acc, curr) => acc + curr.Quantity, 0);

    console.log("WM Total Qty " , totalQty);
}

sumWM();